### ISSUE TITLE
More Robust Handling of Mutes

### ISSUE THREAD

**Issue by buttercat1791** [mleku/realy#3]
The [`AcceptEvent()`](https://github.com/mleku/realy/blob/4a3d7c0a2243dfab87fe6a05a987406c82b90926/cmd/realy/app/implementation.go#L57-L116) function in `cmd/realy/app/implementation.go` currently blocks events sent to the relay based on whether the event author's pubkey is in a mute list of one of the relay owners.

Given that mute lists are often inadvertently deleted as users move between various clients, this is not the most robust way to ensure mutes are correctly handled.

It would probably be better to allow owners of the relay to edit a custom mutelist (which may or may not itself be a Nostr event) that is used only by the relay.  This keeps a strong separation of concerns between the owners' mutes and the npubs which should be rejected by the relay.

Likewise, only accepting events from npubs on the owners' follow lists presents similar concerns.  Allow lists should be unique to the relay, rather than shared with the relay owners' npubs.

**Comment by mleku** [comment]
it would be possible to prevent the owner mute events being deleted and satisfy the same need here

the allow list only controls read/write access with auth enabled, it does not prevent writing of events from any other npub except the ones in the mute lists

i will make a patch to prevent the deletion of active owner mute lists in the accept event handling of deletes as this is where i can check the npub of the event

**Comment by mleku** [comment]
this has turned out to be a really important thing to check on, as the delete implementation is not enforcing safe invariants

it was:

- allowing users to delete other users events
- allowing the deletion of delete events
- allowing the deletion of future event matches for the case of a tags
- allowing a tags to match on non-parameterized replaceable event kinds

i have declined to implement the "k" tag delete feature as i think that is too indistriminate to be safe for users, they will not realise just how much it might destroy and a malicious party may do this for the lulz

the actual point of the issue though, i am resolving this by having the event IDs stored and a tags with follow and mute kind in a delete from the owners will not be honored either for the same reason as the issue

**Comment by mleku** [comment]
just to be clear, k tags are annotations, they don't mean "delete all this kind"
